language: java

install:
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install ant -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install openfl
  - haxelib install hxcpp
  - haxelib install format
  - haxelib install svg
  - haxelib install dox
  - haxelib install mlib
  - haxelib install mcover
  - haxelib install hamcrest
  - haxelib install munit

before_script:
  - cd $TRAVIS_BUILD_DIR/haxeBigInteger

script:
  - ant clean
  - ant build
  - ant test