language: java

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32 -extension GLX"
  - "export AUDIODEV=null"
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update

install:
  - sudo apt-get install -qq flashplugin-installer -y --force-yes
  - sudo apt-get install haxe -y --force-yes > /dev/null
  - sudo apt-get install ant -y --force-yes > /dev/null
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib > /dev/null
  - haxelib install lime > /dev/null
  - haxelib install lime-tools > /dev/null
  - haxelib install openfl > /dev/null
  - haxelib install hxcpp > /dev/null
  - haxelib install format > /dev/null
  - haxelib install svg > /dev/null
  - haxelib install dox > /dev/null
  - haxelib install mlib > /dev/null
  - haxelib install mcover > /dev/null
  - haxelib install hamcrest > /dev/null
  - haxelib install munit > /dev/null

before_script:
  - cd $TRAVIS_BUILD_DIR/haxeBigInteger

script:
  - ant clean
  - ant build
  - haxelib run munit test test.hxml -as3 -norun -result-exit-code